#!/usr/bin/env python3
"""gen_docs.py -- generate the CLI reference FROM the CLIs' own --help output,
so the documented command signatures can't drift from the code (they're derived,
not hand-written).

    python3 cli/gen_docs.py            # regenerate the block in each target doc
    python3 cli/gen_docs.py --check    # exit 1 if any target's block is stale

It replaces the region between these markers in each target file:
    <!-- BEGIN cli-reference (generated by cli/gen_docs.py -- DO NOT EDIT) -->
    ...
    <!-- END cli-reference -->

The CLI list is every `*.py` in `cli/` (globbed, not hard-coded) -- adding a new CLI
there is automatically picked up next regen, so the reference can't silently miss one.
`check_all` runs `--check`, so a changed CLI whose docs weren't regenerated is a red
gate. Pure stdlib; runs under any python3. COLUMNS is pinned so argparse wrapping is
deterministic across environments.
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CLI_DIR = REPO / "cli"
BEGIN = "<!-- BEGIN cli-reference (generated by cli/gen_docs.py -- DO NOT EDIT) -->"
END = "<!-- END cli-reference -->"
TARGETS = [REPO / ".claude" / "rules" / "agentic-workflow.md"]


def _clis() -> list[str]:
    """Every CLI in cli/ -- globbed so a new one can't be silently missed."""
    return sorted(p.name for p in CLI_DIR.glob("*.py"))


def _usage(argv: list[str]) -> str:
    """The `usage:` block from `python3 cli/<argv> --help`."""
    env = {**os.environ, "COLUMNS": "100"}  # pin wrapping -> deterministic output
    r = subprocess.run(
        [sys.executable, str(CLI_DIR / argv[0]), *argv[1:], "--help"],
        cwd=REPO,
        capture_output=True,
        text=True,
        env=env,
    )
    lines: list[str] = []
    grabbing = False
    for ln in r.stdout.splitlines():
        if ln.startswith("usage:"):
            grabbing = True
        if grabbing:
            if ln.strip() == "" and lines:
                break
            lines.append(ln)
    return "\n".join(lines).strip()


def _render() -> str:
    blocks: list[str] = []
    for cli in _clis():
        top = _usage([cli])
        blocks.append(top)
        m = re.search(r"\{([^}]+)\}", top)  # subcommand list, if any
        if m:
            for sub in m.group(1).split(","):
                blocks.append(_usage([cli, sub]))
    body = "\n\n".join(blocks)
    return f"\n```text\n{body}\n```\n"


def _replace(text: str, content: str) -> str:
    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.DOTALL)
    return pattern.sub(BEGIN + content + END, text)


def main() -> int:
    ap = argparse.ArgumentParser(prog="gen_docs.py")
    ap.add_argument("--check", action="store_true", help="exit 1 if any target's block is stale")
    args = ap.parse_args()
    check = args.check
    content = _render()
    stale: list[str] = []
    for path in TARGETS:
        if not path.exists():
            print(f"gen_docs: target missing: {path}", file=sys.stderr)
            return 1
        text = path.read_text()
        if BEGIN not in text or END not in text:
            print(f"gen_docs: markers missing in {path.name}", file=sys.stderr)
            return 1
        new = _replace(text, content)
        if new == text:
            continue
        if check:
            stale.append(path.name)
        else:
            path.write_text(new)
            print(f"updated {path.name}")
    if check and stale:
        print(
            f"gen_docs: STALE cli-reference in {', '.join(stale)} — run `python3 cli/gen_docs.py`",
            file=sys.stderr,
        )
        return 1
    print("cli-reference up to date" if check else "done")
    return 0


if __name__ == "__main__":
    sys.exit(main())
