#!/usr/bin/env python3
"""gen_docs.py -- generate the CLI reference FROM the scripts' own --help output,
so the documented command signatures can't drift from the code (they're derived,
not hand-written).

    python3 scripts/gen_docs.py            # regenerate the block in each target doc
    python3 scripts/gen_docs.py --check    # exit 1 if any target's block is stale

It replaces the region between these markers in each target file:
    <!-- BEGIN cli-reference (generated by scripts/gen_docs.py -- DO NOT EDIT) -->
    ...
    <!-- END cli-reference -->

`check_all` runs `--check`, so a changed CLI whose docs weren't regenerated is a red
gate. Pure stdlib; runs under any python3. COLUMNS is pinned so argparse wrapping is
deterministic across environments.
"""

from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
BEGIN = "<!-- BEGIN cli-reference (generated by scripts/gen_docs.py -- DO NOT EDIT) -->"
END = "<!-- END cli-reference -->"
TARGETS = [REPO / ".claude" / "rules" / "agentic-workflow.md"]
# user-facing CLIs that expose an argparse --help (guard/hook/check_all aren't CLIs)
CLIS = ["task.py", "land.py", "review.py", "log.py", "rehydrate.py"]


def _usage(argv: list[str]) -> str:
    """The `usage:` block from `python3 scripts/<argv> --help`."""
    env = {**os.environ, "COLUMNS": "100"}  # pin wrapping -> deterministic output
    r = subprocess.run(
        [sys.executable, str(REPO / "scripts" / argv[0]), *argv[1:], "--help"],
        cwd=REPO,
        capture_output=True,
        text=True,
        env=env,
    )
    lines: list[str] = []
    grabbing = False
    for ln in r.stdout.splitlines():
        if ln.startswith("usage:"):
            grabbing = True
        if grabbing:
            if ln.strip() == "" and lines:
                break
            lines.append(ln)
    return "\n".join(lines).strip()


def _render() -> str:
    blocks: list[str] = []
    for cli in CLIS:
        top = _usage([cli])
        blocks.append(top)
        m = re.search(r"\{([^}]+)\}", top)  # subcommand list, if any
        if m:
            for sub in m.group(1).split(","):
                blocks.append(_usage([cli, sub]))
    body = "\n\n".join(blocks)
    return f"\n```text\n{body}\n```\n"


def _replace(text: str, content: str) -> str:
    pattern = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.DOTALL)
    return pattern.sub(BEGIN + content + END, text)


def main() -> int:
    check = "--check" in sys.argv[1:]
    content = _render()
    stale: list[str] = []
    for path in TARGETS:
        if not path.exists():
            print(f"gen_docs: target missing: {path}", file=sys.stderr)
            return 1
        text = path.read_text()
        if BEGIN not in text or END not in text:
            print(f"gen_docs: markers missing in {path.name}", file=sys.stderr)
            return 1
        new = _replace(text, content)
        if new == text:
            continue
        if check:
            stale.append(path.name)
        else:
            path.write_text(new)
            print(f"updated {path.name}")
    if check and stale:
        print(
            f"gen_docs: STALE cli-reference in {', '.join(stale)} "
            "— run `python3 scripts/gen_docs.py`",
            file=sys.stderr,
        )
        return 1
    print("cli-reference up to date" if check else "done")
    return 0


if __name__ == "__main__":
    sys.exit(main())
